-- U_MEB_Approve
CREATE TABLE umeb_approve (
    id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO umeb_approve (id, name) VALUES
(1, 'Sie Swan Hian'),
(2, 'Anthony Suhardjo'),
(3, 'Windy Dwiastuti'),
(4, 'Nita Junita'),
(5, '-'),
(6, 'Dalon Tjahjadi'),
(7, 'Akihiko Higuchi'),
(8, 'Hantarman Budiono'),
(9, 'Sugito Mulyana'),
(10, 'Koji Hayashi'),
(11, 'Koichi Morita');


-- U_MEB_Knowing
CREATE TABLE umeb_knowing (
    id CHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO umeb_knowing (id, name) VALUES
('01', 'Sie Swan Hian'),
('02', 'Dalon Tjahjadi'),
('03', 'Windy Dwiastuti'),
('04', 'Nita Junita'),
('05', 'Benny Thiowijaya'),
('06', 'Lim Koman'),
('07', 'Stanley Fujiarto'),
('08', 'Ilham Septian'),
('09', 'Akihiko Higuchi'),
('10', 'Hantarman Budiono'),
('11', 'Sugito Mulyana'),
('12', 'Maja Putra'),
('13', 'Willy'),
('14', 'Heri Sugiyanto'),
('15', 'Anita Afriyanti'),
('16', 'Harry'),
('17', 'Delvi Winosri'),
('18', 'Miftachul Huda'),
('19', 'Koichi Morita'),
('20', 'Christina Eka'),
('21', 'Fahmi Pratama'),
('22', 'Tegar Triatmaja'),
('23', 'Alfadonisio Rickyelfino Z'),
('24', 'Yoshimasa Matsubara');

-- Buyer (SlpCode)
CREATE TABLE buyer (
    id INT NOT NULL,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO buyer (id, code, name) VALUES
(1, 'SOJK', 'Suhardi'),
(2, 'SOSB', 'Windy'),
(3, 'SOSM', 'Indra Djaya'),
(4, 'POBK', 'Indra Ricky'),
(5, 'POBK', 'Nico Widjaja'),
(6, 'POBK', 'Johan'),
(7, 'POSB', 'Feronica'),
(8, 'SOSB', 'Prastiono'),
(9, 'SOSB', 'Office'),
(10, 'SOJK', 'Slamet Supriyadi'),
(11, 'SOJK', 'Wisnu'),
(12, 'SOJK', 'Ahin'),
(13, 'SOJK', 'Office'),
(14, 'POJK', 'Office'),
(15, 'SOSB', 'Nensey'),
(16, 'SOSB', 'Setiawan'),
(17, 'POBK', 'Nita'),
(18, 'SOJK', 'Bendy'),
(19, 'POBK', 'Suparyono'),
(20, 'SOSB', 'Huda'),
(21, 'POBK', 'Dwi Ratnaningsih'),
(22, 'SOJK', 'Yudha Eka Mayang'),
(23, 'POBK', 'Swara Monika'),
(24, 'SOSB', 'Yusuf'),
(25, 'SOJK', 'Santy Hartoyo'),
(26, 'SOSB', 'Joseph'),
(27, 'SOJK', 'Aji Putra Salim'),
(28, 'POBK', 'Ranti'),
(29, 'SOJK', 'Muhammad Farid Fajar'),
(30, 'SOSB', 'Willy'),
(31, 'SOSB', 'Rubben'),
(32, 'POBK', 'Harry'),
(33, 'SOJK', 'Anto'),
(34, 'SOJK', 'Wisnu Aji Baswara'),
(35, 'POSB', 'Lieany'),
(36, 'SOJK', 'Michael Tanuwijaya'),
(37, 'SOJK', 'Toni Wijaya'),
(38, 'POBK', 'Ilham Septian'),
(39, 'POBK', 'Tegar Triatmaja'),
(40, 'SOJK', 'Mohamad Permadi Sudjana'),
(41, 'SOJK', 'Stanley Fujiarto'),
(42, 'SOJK', 'Rudy A Budiman'),
(43, 'SOJK', 'Aji Hidayat'),
(44, 'POSB', 'Office'),
(45, 'SOJK', 'Yoga Wirawan'),
(46, 'POBK', 'Risyana'),
(47, 'SOJK', 'Dani Roberto Ginting'),
(48, 'SOJK', 'Meliana'),
(49, 'SOSB', 'Marianus'),
(50, 'SOJK', 'Anna'),
(51, 'SOJK', 'Atikah'),
(52, 'SOJK', 'Chika'),
(53, 'SOJK', 'Benny Tobing'),
(54, 'POBK', 'Irnia Setiawan'),
(55, 'POBK', 'Adam Bahfen'),
(56, 'SOJK', 'Arief Teguh'),
(57, 'SOJK', 'Prio Utomo'),
(58, 'SOJK', 'Lim Koman'),
(59, 'POBK', 'Pratiwi Anggar Kasih'),
(60, 'SOJK', 'Bendri'),
(61, 'POBK', 'Atika Damayanti'),
(62, 'SOSB', 'Misbahul Munir'),
(63, 'SOJK', 'Dedy Riyanto'),
(64, 'SOJK', 'Nico Agustiawan'),
(65, 'SOJK', 'Muhamad Saman'),
(66, 'SOJK', 'Monica Tiominar'),
(67, 'SOJK', 'Muh Saleh Kurdin'),
(68, 'SOJK', 'Eka B Pertiwi'),
(69, 'SOJK', 'Asdi Astoba'),
(70, 'SOJK', 'Ali Sunandar'),
(71, 'SOJK', 'Doddy Arvian'),
(72, 'SOSB', 'Dedy Riyanto'),
(73, 'SOJK', 'Indra Wahyu Saputra'),
(74, 'SOJK', 'Wigrha Rizky'),
(75, 'POBK', 'Alfadonisio Rickyelfino Z'),
(76, 'SOJK', 'Stievano Timoty Fredrik'),
(77, 'SOJK', 'Elyzabet Halim (Office)'),
(78, 'SOJK', 'Stefanie'),
(79, 'SOJK', 'Khalid (Office)');